# Generated by Django 4.1.5 on 2023-06-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
