# Generated by Django 4.1.3 on 2023-06-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('announcement', '0002_announcement_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
