# Generated by Django 4.1.3 on 2023-06-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcement_view_count_announcement_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
